---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: tex_template_rmd.tex
title: "Introduction"
author: 
  - name: Matt Barreto
    affiliation: University of California-Los Angeles 
  - name: Marcel Roman 
    affiliation: University of California-Los Angeles
  - name: Hannah Walker
    affiliation: Rutgers University 
date: "`r format(Sys.time(), '%m/%d/%Y')`"
abstract: This is an introduction to the WPSA/MPSA paper we are presenting on the effects of contact with imimgration enforcement on political participation and policy attitudes. 
keywords: "Immigration, Law Enforcement, Political Participation, Policy Feedback"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 10pt
spacing: single
bibliography: references.bib
biblio-style: apsr
---

\pagebreak


\doublespacing

\pagebreak

# Introduction 

Outline: 

The unifying hook: Proximal contact with the criminal justice system works through a sense of injustice around the system to impact political attitudes and behaviors. Scholars likewise demonstrate that prximal contact with immigration enforcement likewise impacts the health and well being particularly of members of the Latinx community, attitudes towards government and participation. However, in the area of immigration little research examines the underlying causal mechanisms that connect proximal contact with immigration to attitudinal and participatory outcomes. This raises a number of questions:

Q1) Does a sense of injustice underly the connection between proximal contact and attitudes and behaviors in the area of immigration enforcement?

A1) A sense of injustice arising from proximal experiences with immigration enforcement should yield less punitive attitudes

A2) A sense of injustice arising from proximal experiences with immigration enforcement should prompt system challenging behavior, i.e. protest

Q2) Does the effect of proximal contact with immigration enforcement on attitudes and behaviors among Latinos translate to other racial subgroups, to whom the issue may be of lesser import? 

A3) The impact of a sense of injustice arising from proximal experiences with immigration enforcement should primarily hold among members of the Latinx community, who have been targeted by immigration enforcement for heightened scrutiny. These effects may also hold for Black Americans, who have a long history of conflict with and targeting by law enforcement. These effects may also hold for Asian Americans, a large portion of whom have ties to the immigrant experience. Whites are both less likely to have proximal contact of any kind, and to view law enforcement in a negative light than are their nonwhite counterparts. Nevertheless, in the instance that they hold a sense of injustice around immigration, the size of the impact should be smaller than it is for non-white groups. 

######

What are the effects of immigration enforcement on political participation and evaluations of immigration policy prescriptions? The extant literature is mixed. Some research suggests that immigration enforcement can have a mobilizing effect on various forms of electoral and non-electoral political behavior [@corneliusdeath2001; @pantojacitizens2001; @whitewhen2016; @zepeda-millanlatino2017]. Other research indicates that immigration enforcement demobilizes political participation and depresses engagement with the state, particularly amongst non-citizens and Latinx [@watsoninside2014; @pedrazaimmigration2015;  @vargasimmigration2015; @vargasmixed-status2016; @potochnicklocal-level2017; @amuedo-dorantesinterior2017]. However, despite work on the link between proximate exposure to non-immigration related law enforcement and political participation [@leeconsequences2014; @walkerextending2014; @walkerfor2017; @walkertargeted:nodate],^[Proximate contact or exposure meaning that an individual knows family members and/or friends that are or have been exposed to law enforcement. There is some research on the effects of knowing someone undocumented on political participation [@streetpolitical2017], but this paper is distinct in that a) it also evaluates the effects of proximate contact with immigration authorities, not just knowing someone undocumented and b) it analyzes not only Latinx populations, but the effects of proximate contact on other racial/ethnic groups.] left unanswered in the literature is an investigation of the effects of proximate contact with immmigration enforcement on both various types of political participation *and* attitudes regarding immigration policy prescriptions.^[Although there is a rich literature on the effects of contact with the criminal justice system on public trust and perceptions of the criminal justice system writ large [@tylertrust2002; @weitzerincidents2002; @engelcitizens2005; @peffleyjustice2010; @lermanarresting2014].] Moreover, there is little attention paid to the mechanisms that motivate individual behavior in response to contact with immigration enforcement.^[For an exception, see @whitewhen2016, who leverages CCES data and finds that the reason Latinx are mobilized after the implementation of anti-immigrant policy has more to do with mobilization by parties instead of direct responses to the policy threat.] 

This paper fills in the gap by leveraging a survey deployed in 2018 with representative samples of several different racial and ethnic groups to investigate whether or not proximate exposure to immigration enforcement depresses or increases various forms of political participation and if these relationships vary by race and ethnicity. Since the survey instrument included several questions regarding evaluations of immigration policy prescriptions, this paper also provides an assessment of potential policy feedback effects from immigration enforcement on public opinion over immigration policy. In addition, in order to reveal potential individual-level mechanisms that may be motivating political behavior in response to proximate contact, this paper 
investigates both whether or not proximate exposure influences a sense of injustice and how a sense of injustice affects both political participation and immigration policy preferences. Analyzing the link between perceptions of injustice and proximate contact is important since previous research finds that perceptions of injustice and discrimination with respect to the criminal justice system influence how family members and friends respond to proximate exposure [@walkertargeted:nodate]. 

The results indicate that, across all racial categories, proximate contact with immigration enforcement mobilizes non-traditional forms of political participation such as protesting or attending demonstrations, but does not have an effect on traditional forms of participation such as voting. This paper identifies a potential mechanism in showing that non-traditional mobilization may be driven by a perception of an unjust legal and immigration system. Moreover, this paper finds that proximate contact with immigration enforcement may generate changes in how the public perceives immigration policy prescriptions. Proximate contact is associated with a progressive shift in evaluating immigration policy proposals such as comprehensive immigration reform and even abolishing ICE. 
  

Additionally, this paper finds some racial heterogeneity in the effects of proximate contact with immigration enforcement. Interestingly, there are no heterogenous effects by racial or ethnic group category with respect to proximate contact with immigration authorities and political protest, which contradicts previous work on the racially heterogenous effects of exposure to the criminal justice system [@walkerextending2014; @walkertargeted:nodate]. All groups are equally mobilized by proximate exposure to immigration enforcement.^[Albeit the point estimates are larger for non-white groups, with the upper bounds for non-white groups exceeding the upper bounds for whites (with the exception of AAPI).] However, consistent with theories in the extant literature that suggest that targeted populations are more likely to respond politically in the face of policy threat than non-targeted populations [@pantojafear2003; @kangelectoral2017; @laniyonupolitical2018], this paper finds that Latinx are more likely to shift in a progressive direction with respect to evaluations of immigration policy prescriptions than other racial group categories.

This paper makes several contributions. First, given the nature of the sample, there is sufficient statistical power for a cross-racial/ethnic group analysis.^[With 400 respondents for the 5 relevant racial/ethnic group categories: white, black, Latinx, Native American, and AAPI.] Therefore, the sample provides a unique opportunity to study the effects of immigration enforcement on groups that are not only politically underrepresented, but underrepresented when it comes to research on the effects of enforcement, such as Native Americans and Asians. Second, the research question moves beyond merely conceptualizing criminal justice through the policing of black American communities and individuals (e.g. what some scholars would call the ``black/white'' binary, although this understanding is somewhat problematic in the context of immigration policy given the existence of foreign-born black people and black immigrants). Understanding law enforcement through the lens of immigration policy is particularly important given that there are a disproportionate amount of resources devoted to immigration enforcement at the Federal level,^[In 2012, [Congress appropriated \$18 billion for immigration enforcement while it appropriated \$14 billion for all the other major criminal law enforcement agencies combined.](https://www.theatlantic.com/magazine/archive/2018/09/trump-ice/565772/)] it is an increasingly salient issue given the election of Donald Trump, and the U.S. is undergoing a demographic transformation in that the percentage of the foreign-born population is at its highest since 1910.^[According to the Migration Policy Institute, ["The foreign-born share of the U.S. population is at its highest level since 1910, with the approximately 44 million immigrants living in the United States representing 13.5 percent of the overall population....With U.S. fertility rates at a historic low, the Census Bureau projects that net international migration will be the main driver behind U.S. population growth between 2027 and 2038."](https://www.migrationpolicy.org/article/immigrants-us-states-fastest-growing-foreign-born-populations)] Third, while there is some research to suggest that criminal justice policies affect how individuals judge the state, legal system, and criminal justice policy writ large, there is limited research on the effects of immigration enforcement on the evaluation of immigration policy prescriptions. This paper fills in the gap by employing a survey asking respondents to evaluate various proposals that may offer a solution to the immigration status of millions of people residing in the U.S. such as conditional residency for alien minors (the DREAM act), comprehensive immigration reform (CIR), and even abolishing ICE. Fourth, while there is some work on the de(mobilizing) effects of immigration enforcement, much of it is limited to analyzing electoral outcomes such as voting and registration [@whitewhen2016; @amuedo-dorantesinterior2017]. Moreover, much of the work analyzing the determinants of protest activity related to anti-immigrant policies does not take into account prior contact with immigration enforcement officers [@zepeda-millanlatino2017]. This paper fills in this gap, both by analyzing non-electoral political activity as an outcome and accounting for proximate exposure to contact with immigration enforcement officials.

# References

